[package]
name = "chomp"
authors = ["Matt Moradi <matthew.moradi@pdx.edu>", "Bart Massey <bart@cs.pdx.edu>"]
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.txt"

[lib]
name = "chomp_ai"

[[bin]]
name = "chomp"

[dependencies]
prompted = "0.2.7"
